spring.application.name=streaming

# URI de conexión completa (incluye usuario, contraseña y opciones de SRV)
spring.data.mongodb.uri=mongodb+srv://admin_streaming:99NNtyZXs4dpytZW@cluster0.q9au4oc.mongodb.net/streaming_db?retryWrites=true&w=majority&appName=Cluster0

# Opcional: Esto ayuda a ver si el driver está intentando conectar correctamente
logging.level.org.mongodb.driver=DEBUG